#' Generated by roxygen2 (4.1.0.9001): do not edit by hand
#'######################################################################
#' Fit logistic regression to data with formula, simulate a sample of size = size with burnin = burnin using Monte carol methods from the posterior (likelihood) distribution of coefficients. There are two approximate methods used in this function: Normal approximation and Skew-normal approximation.  
#'##################################################################
#' @title Likelihood Modeling for Logistic Regression in Each Subset
#' 
#' 
#' @description Model the posterior distribution of parameters in logistic regression by normal distribution or skew normal distribution, where the prior distribution is the uniform distribution.
#' @param formula 
#' an object of class "formula" (or one that can be coerced to that class): a symbolic description of the model to be fitted. The details of model specification are the same to the formula in lm.
#' @param data 
#' an optional data frame, list or environment (or object coercible by as.data.frame to a data frame) containing the variables in the model. If not found in data, the variables are taken from environment(formula).
#' @param size 
#' the number of MCMC iterations saved (target distribution is the posterior distribution of parameters in the logistic regression)
#' @param burnin 
#' the number of MCMC iterations discarded.
#' @param conf_level 
#' a vector which consists of levels of credible intervals
#' @param approx_method 
#' the method to approximate the posterior distribution such as normal or skew normal, the default one is normal distribution
#' @author Qi Liu
#' @return prob_compare 
#' a dataframe with two columns: approximate probability and true proability. The probability under different credible regions defined by conf_levels is estimated by using Monte Carlo methods
#' @return norm.mean
#' mean parameter of fitted normal distribution
#' @return norm.var
#' variance (covariance) of fitted normal distribution
#' @return sn.xi
#' location parameter of fitted skew normal distribution if approx_method is "SN", Null otherwise
#' @return sn.omega
#' scale parameter of fitted skew normal distributionif approx_method is "SN", Null otherwise
#' @return sn.alpha 
#' shape parameter of fitted skew normal distributionif approx_method is "SN", Null otherwise
#' @examples 
#'x <- matrix(rnorm(1000*5), ncol=5)
#'y <- rbinom(1000,1,0.5)
#'df <- as.data.frame(x)
#'names(df) <- paste("x",1:5,sep="")
#'df$y <- y
#'rst <- LMsubset(y~x1+x2, data =df, size=500, burnin =50, conf_level = seq(0.05, 0.95, 0.05), approx_method = "SN")
#'@seealso
#' \code{\link{subset_approx}}
#'@import sn
#'@import BayesLogit
#'@import MASS
#'@import mvtnorm
#'@import moments
#'@export

LMsubset <- function(formula=formula, data=data,size, burnin, conf_level, approx_method=approx_method){
  mf <- model.frame(formula=formula, data=data)
  x <- model.matrix(attr(mf, "terms"), data=mf)
  y <- model.response(mf)
  rst <- subset_approx(x,y, size, burnin, conf_level, approx_method=approx_method)
  rst
}





